# Generated by Django 4.2.6 on 2023-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
