# Generated by Django 4.2.6 on 2023-10-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_projecttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='primary_image',
            field=models.ForeignKey(blank=True, default='images/default.jpg', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='primary_image', to='base.projectimage'),
        ),
    ]
