# Generated by Django 4.2.6 on 2023-10-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_project_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.projecttype'),
        ),
    ]
